name: Deploy release artifacts

on:
  push:
    branches: [main]

jobs:
  deploy-release:
    name: Deploy Release
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    steps:
      - uses: earthly/actions-setup@v1
        with:
          version: "latest"
      - name: checkout
        uses: actions/checkout@v3
      - name: Build artifacts
        run: earthly +all -SSL_LIBRARY=boringssl
